server:
  port: ${PORT:8081}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  jwt:
    secret: ${JWT_SECRET=FXRI/OrcS4qZ5bV7XUVzyq9oKEn3rZHeD02qdCwq8qc=}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}